server:
  port: 8080

db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: cryptodb
  sslmode: disable

rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest
